### ISSUE TITLE
CCM uses "-mod readonly" when building

### ISSUE THREAD

**Issue by kwoodson** [openshift/cloud-provider-alibaba-cloud#13]
We have strict requirements on our build servers that do not allow any external library downloads. The `-mod readonly` setting here https://github.com/openshift/cloud-provider-alibaba-cloud/blob/master/Makefile#L32 forces dependencies to be downloaded during the build process. This behavior is strictly forbidden.

@gujingit Is this something we can change? Is there a reason why this is done in the upstream repository? We would like to ensure that all necessary files are in the `vendor/` directory for the build process.

cc @elmiko

**Comment by elmiko** [comment]
+1, i think we should change that line to be `-mod vendor` unless there is a strong reason to use the `readonly` form.
