### ISSUE TITLE
cloud-conf configmap expects accesskey and accesssecret to be base64

### ISSUE THREAD

**Issue by kwoodson** [openshift/cloud-provider-alibaba-cloud#5]
@elmiko @JoelSpeed
The installer for Alibaba is creating credentials and placing them in the `cloud-conf` configmap. The cloud-conf looks like this:
```
  cloud.conf: "{\n\t\"Global\": {\n\t\t\"kubernetesClusterTag\": \"\",\n\t\t\"nodeMonitorPeriod\":
    0,\n\t\t\"nodeAddrSyncPeriod\": 0,\n\t\t\"uid\": \"\",\n\t\t\"vpcid\": \"\",\n\t\t\"region\":
    \"us-east-1\",\n\t\t\"zoneid\": \"\",\n\t\t\"vswitchid\": \"\",\n\t\t\"clusterID\":
    \"test-jdbm2\",\n\t\t\"routeTableIDs\": \"\",\n\t\t\"serviceBackendType\": \"\",\n\t\t\"disablePublicSLB\":
    false,\n\t\t\"accessKeyID\": \"<redacted>\",\n\t\t\"accessKeySecret\":
    \"<redacted>\"\n\t}\n}\n"
```

The CCM will read the cloud-conf configmap once openshift/cluster-cloud-controller-manager-operator/pull/94 is fixed with the correct configmap and the code changes are merged. 

I am seeing this error when attempting to run the CCM with `--v=8` set in the CCM environment:
```
I0903 01:13:48.956363       6 alicloud.go:132] Alicloud: Try Accesskey and AccessKeySecret from config file.
E0903 01:13:48.956453       6 cloudprovider-alibaba-cloud.go:49] Run CCM error: verify ccm config: cloud provider could not be initialized: could not init cloud provider "alicloud": illegal base64 data at input byte 28
```
I was able to track that code down to this location and it appears the expectation here is that the `accessKeyID` and the `accessKeySecret` are base64 encoded.
https://github.com/openshift/cloud-provider-alibaba-cloud/blob/master/cloud-controller-manager/alicloud.go#L125-L137

Either the key needs to be written by the installer  ( https://github.com/openshift/installer/pull/5018/files#diff-3c9c46884bade6b4d4d801ef3b69fdf08628e35dacc56deb4f1f5d67d45f1c24R9-R31 ) to base64 or this needs to just accept the value as is. This is currently blocking the CCM and allowing masters to achieve their `Ready` state.

Let me know what you think.

**Comment by JoelSpeed** [comment]
> Alibaba is creating credentials and placing them in the cloud-conf configmap

Do the credentials absolutely have to be in a configmap? This seems like a security risk to me that we should be trying to avoid.

At the moment, Azure has this limitation as well (at least on stack hub) so we take the credentials from a secret, and inject them into the config as the container starts. I think this is probably a preferable approach over what we have today, but ideally I think we should teach the alibaba CCM to read the credentials from environment variables (we are poking for this for azure too) to allow us to keep the credentials in a secret and the rest of the config in a configmap.
