### ISSUE TITLE
alicloud: unable to split instanceid and region from providerID

### ISSUE THREAD

**Issue by kwoodson** [openshift/cloud-provider-alibaba-cloud#9]
I am attempting to deploy https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/119 which deploys the Alibaba CCM. I have been placing debug statements in attempt to figure out why the CCM is not registering the master nodes in an OpenShift cluster.

The call is getting the name correctly from the v1.Node here https://github.com/openshift/cloud-provider-alibaba-cloud/blob/master/cloud-controller-manager/controller/node/controller.go#L604 and attempting to get the providerID

The error message I'm seeing is:
```
failed to get provider ID for node test-8bv8v-master0 at cloudprovider: failed to get instance ID from cloud provider: alicloud: unable to split instanceid and region from providerID, error unexpected providerID=test-8bv8v-master0
```
This is occurring here:
https://github.com/openshift/cloud-provider-alibaba-cloud/blob/master/cloud-controller-manager/instances.go#L88

Alibaba's code expects the providerID to be in a specific `alicloud://` prefix or be in `<region>.<node name>` format. 

We need some assistance in determining the expectation of the providerID variable in question.

@gujingit Would you mind providing some assistance on how we may proceed?

**Comment by gujingit** [comment]
https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/master/docs/getting-started.md

**Comment by gujingit** [comment]
Run these commands in your all ECS instances which belong to the Kubernetes cluster
$ META_EP=http://100.100.100.200/latest/meta-data
$ echo `curl -s $META_EP/region-id`.`curl -s $META_EP/instance-id`

Then, patch nodes
kubectl patch node ${NODE_NAME} -p '{"spec":{"providerID": "${NODE_NAME}"}}'

**Comment by kwoodson** [comment]
We can address this with https://github.com/openshift/machine-config-operator/pull/2777
